# Generated by Django 4.0.5 on 2022-06-23 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amechanic', '0002_rename_name_location_location_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ManyToManyField(to='amechanic.location'),
        ),
    ]
