# Generated by Django 4.0.5 on 2022-06-22 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amechanic', '0003_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='affordability',
            new_name='customer_relations',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='affordability_average',
            new_name='customer_relations_average',
        ),
    ]
